### ISSUE TITLE
New version of IIPImage - with RPM & DEB packages

### ISSUE THREAD

**Issue by klokan** [klokantech/iiifserver#17]
We created new binaries for IIPImage JPEG2000 server and automated the whole binary release process for multiple platforms, for multiple linux distros including RedHat linux, with a Jenkins CI infrastructure to be able to create and automatically test the binaries for future releases and ensure the binaries are correct before deployment on production systems.

The new binaries are now powered by the reviewed and rewritten IIIF implementation made by Ruven (heavily inspired by KlokanTech's implementation, but not merged directly).

Download latest RPM and DEB packages from the page:
http://www.iiifserver.com/download/

Could you please try this binary - and confirm if a switch to the IIPImage master branch would be a possibility for your online application?

If this would be the case, we would continue the coding on the master branch of IIPImage and further 

Recently we have also acquired the commercial license for Kakadu JPEG2000 and we are testing the SpeedPack performance as well.

**Comment by gpetz** [comment]
it seems to me that libkdu.so is not a symbolic link, it's a copy of  libkdu_v75R.so:
````
georg@fue-georg:~/Downloads/usr/lib64$ ls -l
insgesamt 2104
-rwxr-xr-x 1 georg georg 1074016 Nov  5 17:44 libkdu.so
-rwxr-xr-x 1 georg georg 1074016 Nov  5 17:44 libkdu_v75R.so
````

**Comment by klokan** [comment]
The symlink as well as linking with kdu has been fixed in recent versions of .rpm and .deb.
There is autobuild process configured in Jenkins now.
