### ISSUE TITLE
Wrong generation of colours for last tile in an image

### ISSUE THREAD

**Issue by jump-soft** [klokantech/iiifserver#22]
Hi,

when we are zooming an image, we are getting a glitch for last tile at some zoom levels.
![glitch_1](https://cloud.githubusercontent.com/assets/17475189/13321981/932daa0e-dbd2-11e5-942e-e0c42aee5ded.png)

Same problem is visible also here:
http://iiif.klokantech.com/demo.jp2/7750,7300,50,1000/6,/0/native.jpg

For width of 7 pixels and above it is OK, width of 6 pixels and less is problematic.

We assume, it is casued by some round() function, because it is visible only at some zoom levels for the last tile (most right tile) of an image.

**Comment by klokan** [comment]
Can you please try it with the latest binary from http://www.iiifserver.com/?

Live demo at: http://demo.iiifhosting.com/iiif/demo

I believe this issue has been already fixed recently. Please confirm.

**Comment by jump-soft** [comment]
I try latest version and it's OK now. thanks

**Comment by jump-soft** [comment]
Is the binary version from http://www.iiifserver.com/download/ the same as here on github?

Because we need compile it from sources.

thanks

**Comment by klokan** [comment]
We offer automatically compiled and updated binaries for Microsoft Windows, various Linux distributions, and docker - and can provide license for Kakadu for JPEG2000 decoding or encoding functionality even for commercial use.
To use the libraries without watermark you need activation code with valid maintenance subscription from us.

Binaries are created from this GitHub repository - by merging individual branches and patches into the standard IIPSRV master branch. If you want to compile from sources, you can - but we do not provide support for such use case.

It seems the technical issue reported here is resolved and this ticket is now closed. If you are interested in acquiring our maintenance activation code, please contact info@klokantech.com and describe your use case.
