### ISSUE TITLE
Broken demo image in the new iiifserver installation 

### ISSUE THREAD

**Issue by yuxifu** [klokantech/iiifserver#23]
We are trying to upgrade from IIPImage Server 0.9.9 to IIIFServer 1.0.  However, the demo image of the fresh installation was not rendered correctly. Here is the screen shot:
https://www.flickr.com/photos/89055258@N00/24758355214/in/dateposted-public/lightbox/

![24758355214_545103554a_h](https://cloud.githubusercontent.com/assets/59284/13434347/c5110a5a-dfd5-11e5-92b7-f4a0e4de9df6.jpg)

We tested on 4 machines having similar hardware configuration:
OS: Windows 7 enterprise 64 bits, Service Pack 1, English
Hardware: 4-32G RAM

Steps to test:
1. Download the installer at http://downloads.klokantech.com/iiifserver/iiifserver-1.0.0-165.win-IIS.x86_64.exe
2. Install. Follow the on screen instructions.  All default.
3. http://localhost/iiif/demo popped up automatically by the installer.
4. no difference in different browsers.  Tested with IE, FF, and Chrome. All latest versions.

It's worth to mention that we tested on four machines. Two of them actually worked correctly. But two others showed the broken images (no matter it's the demo image or our own images).

Another point worth mentioning is that the two machines worked correctly were not for development, having no dev tools installed such as Visual Studio.

**Comment by klokan** [comment]
We are not able to reproduce the problem on our Windows test machines.

On our Windows instances it always run correctly - any clue what is different on the two machines from four where you can see the problem?

**Comment by yuxifu** [comment]
Tested more. Total 6 Windows 7 machines. 4 of them did not show the demo image correctly. I did not find obvious hardware or software differences among those machines.

**Comment by yuxifu** [comment]
Actually, two machines for testing were Windows Server 2012 R2.

**Comment by klokan** [comment]
Error reproduced on virtualised Windows 7 Professional SP1 64bit virtual machine. We are starting to work on an analyse - which may lead to a fix.

**Comment by MartinMikita** [comment]
We have found problem and fix it. Please, try new binary downloaded from http://downloads.klokantech.com/iiifserver/iiifserver-1.0.0-180.win-IIS.x86_64.exe

**Comment by yuxifu** [comment]
The new binary works like a charm :-)

Thank you guys!
