### ISSUE TITLE
Cannot open demo page

### ISSUE THREAD

**Issue by tangfucius** [klokantech/iiifserver#25]
Hi, I installed iiifserver on Ubuntu 14.04 following these instructions:
http://www.iiifserver.com/how-to/installation-linux/

But `http://localhost/iiif/` gives me a 'not found' message. However, `http://localhost/fcgi-bin/iiifserver.fcgi` shows me a page that asks me to get a license key for JPEG2000. How can I get it to work, and do I need to buy a license for Kakadu in order to use iiifserver (I thought the package comes with JPEG2000 support already).

**Comment by MartinMikita** [comment]
Hello,

If you are able to see `http://localhost/fcg-bin/iiifserver.fcgi`, then it means, you have not properly installed your web server. If you are using Apache 2, you need to manually enable `rewrite` module, as it is described on how-to page you have linked.

You may use IIIFServer as a free plan - with IIIFServer.com watermark. See more details [in pricing page](http://www.iiifserver.com/pricing/)

**Comment by tangfucius** [comment]
Hmm I already ran 
`sudo apt-get install apache2 libapache2-mod-fcgid
sudo a2enmod rewrite` 
as stated on the how-to page, but visiting `http://localhost/iiif/` still gives me `The requested URL /iiif/ was not found on this server`. Are there no other config files I need to change/activate?
`/etc/apache2/mods-available/iiifserver.conf` seems fine though.

**Comment by MartinMikita** [comment]
Have you restarted apache2 service, as it was suggested after enabling rewrite mod?
```
To activate the new configuration, you need to run:
  service apache2 restart
```

**Comment by tangfucius** [comment]
yeah enabled and restarted multiple times. is it supposed to work as simply
as the guide?

2017/03/17 午後4:35 "Martin Mikita" <notifications@github.com>:

**Comment by MartinMikita** [comment]
There was an incorrect rule for Apache 2. We have fixed it, tested it and it is inside new packages: download the latest IIIFServer at https://www.iiifserver.com/download/
